development:
  adapter: postgresql
  encoding: utf8
  database: picard
  host: localhost
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: picard
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: picard
  pool: 5
  username:
  password:
